"use client";

import { Activity, ArrowLeft, ChartNoAxesColumn, Dumbbell, HeartPulse, House, Pill, Salad, Settings, Target, type LucideIcon } from "lucide-react";
import { type TouchEvent, useEffect, useMemo, useRef, useState } from "react";

type WorkoutType = "none" | "strength" | "run" | "cycle" | "sport" | "mobility";
type Entry = { date: string; habits: Record<string, boolean>; water: number; movement: number; workoutType: WorkoutType; note: string };
type State = { entries: Record<string, Entry> };
type OuraWorkout = Record<string, unknown>;
type Oura = { sleepScore?: number; readinessScore?: number; activityScore?: number; steps?: number; recentWorkouts?: string[]; workouts?: OuraWorkout[]; syncedAt?: string };
type Tab = "today" | "exercise" | "prescription" | "trends" | "history" | "settings";
type Prescription = { mode: string; title: string; reason: string; moves: string[]; recovery: string[]; food: string[] };
type InsightMetric = { id: string; label: string; completedDays: number; suggestion: string };

const STORAGE_KEY = "personal-wellness-journal";
const VIEW_STORAGE_KEY = "well-being-active-view";
const APP_TIME_ZONE = "America/Chicago";
const HABITS = [{ id: "morning", label: "Morning routine", detail: "Start without the scroll" }, { id: "outside", label: "Time outside", detail: "A little daylight counts" }, { id: "movement", label: "Move your body", detail: "Walk, train, stretch" }, { id: "winddown", label: "Evening wind-down", detail: "Make room for rest" }];
const tabs: { id: Tab; label: string }[] = [{ id: "today", label: "Today" }, { id: "exercise", label: "Exercise" }, { id: "prescription", label: "Prescription" }, { id: "trends", label: "Insights" }, { id: "settings", label: "Settings" }];

function dateKey(date = new Date()) { const parts = Object.fromEntries(new Intl.DateTimeFormat("en-US", { timeZone: APP_TIME_ZONE, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(date).map((part) => [part.type, part.value])); return `${parts.year}-${parts.month}-${parts.day}`; }
function createEntry(date: string): Entry { return { date, habits: Object.fromEntries(HABITS.map((habit) => [habit.id, false])), water: 0, movement: 0, workoutType: "none", note: "" }; }
function normalize(entry: Partial<Entry>, date: string): Entry { return { ...createEntry(date), ...entry, habits: { ...createEntry(date).habits, ...entry.habits } }; }
function score(entry: Entry, oura?: Oura | null) { const personal = (Object.values(entry.habits).filter(Boolean).length / HABITS.length + Math.min(entry.water / 8, 1)) / 2; const signals = [oura?.readinessScore, oura?.sleepScore, oura?.activityScore].filter((v): v is number => typeof v === "number"); return Math.round((signals.length ? signals.reduce((a, b) => a + b, 0) / signals.length / 100 * .65 + personal * .35 : personal) * 100); }
function scoreBand(value: number) { return value >= 80 ? "score-band-high" : value >= 60 ? "score-band-steady" : "score-band-low"; }
function scoreState(value: number) { return value >= 80 ? "Well cared for" : value >= 60 ? "Building care" : "Needs care"; }
function scoreMessage(value: number) { return value >= 80 ? "Your daily care is landing well. Keep protecting the routines that help you feel grounded." : value >= 60 ? "Your care is taking shape. One or two intentional choices can make the day feel more supported." : "Some of your care needs more attention today. Choose one gentle action, like water, movement, daylight, or rest."; }
function prescription(entry: Entry, history: Entry[], oura: Oura | null, limit: string, equipment: string, override: string): Prescription {
  const readiness = oura?.readinessScore ?? 70;
  const sleep = oura?.sleepScore ?? 70;
  const hardRun = [...history, entry].some((item) => item.workoutType === "run" && item.movement >= 35) || Boolean(oura?.recentWorkouts?.some((item) => /run|cycle|hike/i.test(item)));
  const recentStrength = [...history, entry].some((item) => item.workoutType === "strength") || Boolean(oura?.recentWorkouts?.some((item) => /strength|weight|lift|gym/i.test(item)));
  if (override === "recover" || readiness < 60 || sleep < 60) return { mode: "Recovery", title: "Recover on purpose", reason: "Your recent recovery signals call for low intensity and more room to rebuild.", moves: ["20 min easy walk", "2 rounds: 8 cat-cows + 8 world's greatest stretches per side", "10 min gentle mobility"], recovery: ["Breathwork: 5 min, inhale for 4 sec and exhale for 6 sec", "Meditation: 10 min guided body scan", "Keep effort conversational and finish feeling better"], food: ["Protein at each meal: eggs, yogurt, chicken, fish, tofu", "Colorful produce, soup, rice, potatoes, and steady fluids"] };
  if (readiness < 75 || sleep < 75) return { mode: "Active recovery", title: "Keep the body moving", reason: "Your signals support movement, but today is better suited to circulation and mobility than hard training.", moves: ["25-35 min easy walk, bike, or swim", "3 rounds: 8 world's greatest stretches per side", "2 rounds: 10 glute bridges + 8 dead bugs per side"], recovery: ["10 min easy stretching for hips, calves, and upper back", "Breathwork: 5 min of slow nasal breathing with a longer exhale", "Meditation: 8 min guided mindfulness", "Finish with energy left in the tank; no pushing through fatigue"], food: ["Protein at each meal: eggs, yogurt, chicken, fish, tofu", "Steady carbs: oats, rice, potatoes, fruit", "Hydrate consistently and include colorful produce"] };
  if (override === "push" || (readiness >= 82 && sleep >= 80 && !recentStrength)) return { mode: "Build", title: "Train with intent", reason: "Your sleep and readiness support a focused training day.", moves: ["Warm-up: 6 min brisk walk + mobility", equipment === "none" ? "Tempo squats: 4 x 10" : "Squat or leg press: 4 x 6-8", equipment === "none" ? "Push-ups: 4 x 8-15" : "Bench press: 4 x 6-10", "Romanian deadlift: 3 x 8-10", "Farmer carry: 4 x 40 sec"], recovery: ["8-10 min full-body stretching", "Breathwork: 3 min, inhale for 4 sec and exhale for 6 sec", "Meditation: 5 min post-workout reset", "Easy walk later if stiff; protect tonight's sleep"], food: ["Protein at every meal: beef, poultry, fish, eggs, dairy, tofu", "Add carbs around training: oats, rice, potatoes, fruit", "Have a protein plus carb meal after training"] };
  if (hardRun) return { mode: "Balance", title: "Build the base", reason: "Recent activity has been demanding, so today balances strength and control.", moves: ["Goblet squat: 3 x 10", "Push-ups: 3 x 8-12", "1-arm row: 3 x 10 per side", "Dead bug: 3 x 8 per side", "10 min easy walk"], recovery: ["5-8 min calves, hips, and hamstrings", "Breathwork: 5 min of slow nasal breathing", "Meditation: 8 min guided body scan", "Keep the next session easy if soreness rises"], food: ["Protein-forward meals: lean meat, fish, cottage cheese, beans", "Moderate carbs: oats, potatoes, rice, fruit", "Add vegetables and healthy fats"] };
  return { mode: "Steady", title: "Move and reset", reason: `A moderate session fits your current signals. ${limit} minute target.`, moves: ["5 min easy warm-up", "Run/walk intervals: 8 x 1 min steady, 1 min easy", equipment === "none" ? "Reverse lunges: 3 x 8 per side" : "Split squat: 3 x 8 per side", "Plank: 3 x 30-45 sec"], recovery: ["Gentle stretch for calves, hips, chest, and back", "Breathwork: 5 min, inhale for 4 sec and exhale for 6 sec", "Meditation: 5-8 min guided mindfulness"], food: ["Balanced plates: protein, whole-food carbs, vegetables", "Choose chicken, lentils, eggs, yogurt, rice, fruit, and greens", "Pair snacks with protein"] };
}
function workoutName(workout: OuraWorkout) { return String(workout.type || workout.activity || workout.name || workout.label || "Workout").replaceAll("_", " "); }
function workoutDate(workout: OuraWorkout) { const raw = String(workout.day || workout.start_datetime || workout.start_time || ""); if (!raw) return ""; const date = new Date(raw.includes("T") ? raw : `${raw}T12:00:00`); return Number.isNaN(date.getTime()) ? raw : date.toLocaleDateString("en-US", { month: "short", day: "numeric" }); }
function workoutDateKey(workout: OuraWorkout) { return String(workout.day || workout.start_datetime || workout.start_time || "").match(/^\d{4}-\d{2}-\d{2}/)?.[0] || ""; }
function workoutDuration(workout: OuraWorkout) { const seconds = Number(workout.duration || workout.duration_seconds); return Number.isFinite(seconds) && seconds > 0 ? `${Math.round(seconds / 60)} min` : ""; }
function workoutSummary(workout: OuraWorkout) { const details = [workout.intensity ? String(workout.intensity).replaceAll("_", " ") : "", Number(workout.distance) > 0 ? `${(Number(workout.distance) / 1609.34).toFixed(1)} mi` : "", Number(workout.calories) > 0 ? `${Math.round(Number(workout.calories))} kcal` : ""].filter(Boolean); return details.length ? details.join(" · ") : "Auto-detected workout"; }
function planDayType(plan: Prescription) { return plan.mode === "Build" ? "Strength day" : plan.mode === "Balance" ? "Balance day" : plan.mode === "Recovery" ? "Recovery day" : plan.title === "Keep the body moving" ? "Mobility day" : "Run day"; }
function tabIcon(id: Tab): LucideIcon { return id === "today" ? House : id === "exercise" ? Dumbbell : id === "prescription" ? Pill : id === "trends" ? ChartNoAxesColumn : Settings; }
function dailyCompletion(entry: Entry, hasOuraWorkout: boolean) {
  const habitsDone = HABITS.filter((habit) => habit.id === "movement" ? entry.habits[habit.id] || hasOuraWorkout || entry.workoutType !== "none" : entry.habits[habit.id]).length;
  return Math.round((habitsDone + Math.min(entry.water / 8, 1)) / (HABITS.length + 1) * 100);
}

export default function Home() {
  const [today, setToday] = useState(() => dateKey());
  const [state, setState] = useState<State>({ entries: {} });
  const [oura, setOura] = useState<Oura | null>(null);
  const [weeklyWorkouts, setWeeklyWorkouts] = useState<OuraWorkout[]>([]);
  const [connected, setConnected] = useState(false);
  const [tab, setTab] = useState<Tab>("today");
  const [selectedDate, setSelectedDate] = useState(today);
  const [loaded, setLoaded] = useState(false);
  const [viewLoaded, setViewLoaded] = useState(false);
  const [limit, setLimit] = useState("45");
  const [equipment, setEquipment] = useState("gym");
  const [override, setOverride] = useState("auto");
  const [checkedMoves, setCheckedMoves] = useState<Record<string, boolean>>({});
  const [effort, setEffort] = useState("right");
  const refreshStart = useRef<number | null>(null);
  const refreshDistance = useRef(0);
  const [refreshing, setRefreshing] = useState(false);
  const [refreshProgress, setRefreshProgress] = useState(0);
  const previousToday = useRef(today);

  useEffect(() => { const timer = window.setInterval(() => { const currentDate = dateKey(); setToday((current) => current === currentDate ? current : currentDate); }, 30000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { if (previousToday.current === today) return; const previousDate = previousToday.current; previousToday.current = today; if (selectedDate === previousDate) setSelectedDate(today); }, [selectedDate, today]);
  useEffect(() => { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) { try { const parsed = JSON.parse(saved) as State; setState({ entries: Object.fromEntries(Object.entries(parsed.entries || {}).map(([date, item]) => [date, normalize(item, date)])) }); } catch { window.localStorage.removeItem(STORAGE_KEY); } } setLoaded(true); }, []);
  useEffect(() => { if (loaded) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [loaded, state]);
  useEffect(() => { const saved = window.localStorage.getItem(VIEW_STORAGE_KEY); if (saved) { try { const view = JSON.parse(saved) as { tab?: Tab; selectedDate?: string }; const savedTab = view.tab && tabs.some((item) => item.id === view.tab) ? view.tab : "today"; setTab(savedTab); setSelectedDate(savedTab === "today" ? dateKey() : view.selectedDate || dateKey()); } catch { window.localStorage.removeItem(VIEW_STORAGE_KEY); } } setViewLoaded(true); }, []);
  useEffect(() => { if (viewLoaded) window.localStorage.setItem(VIEW_STORAGE_KEY, JSON.stringify({ tab, selectedDate })); }, [viewLoaded, tab, selectedDate]);
  useEffect(() => { void fetch("/api/integrations/status").then(async (response) => { if (response.ok) setConnected(Boolean((await response.json() as { oura?: boolean }).oura)); }); }, []);
  useEffect(() => { if (!connected) return; void fetch(`/api/integrations/oura/data?date=${selectedDate}`).then(async (response) => { if (!response.ok) return; const data = await response.json() as { sleep?: Record<string, unknown>; readiness?: Record<string, unknown>; activity?: Record<string, unknown>; workouts?: OuraWorkout[] }; const sleep = data.sleep || {}; const readiness = data.readiness || {}; const activity = data.activity || {}; const workouts = data.workouts || []; setOura({ sleepScore: Number(sleep.score) || undefined, readinessScore: Number(readiness.score) || undefined, activityScore: Number(activity.score) || undefined, steps: Number(activity.steps) || undefined, workouts, recentWorkouts: workouts.map(workoutName), syncedAt: new Date().toISOString() }); }); }, [connected, selectedDate]);
  useEffect(() => { if (!connected || tab !== "trends") return; void fetch(`/api/integrations/oura/data?date=${today}`).then(async (response) => { if (!response.ok) return; const data = await response.json() as { workouts?: OuraWorkout[] }; setWeeklyWorkouts(data.workouts || []); }); }, [connected, tab, today]);

  const entry = state.entries[selectedDate] ?? createEntry(selectedDate);
  const recentDates = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(`${today}T12:00:00`); date.setDate(date.getDate() - (6 - index)); return dateKey(date); }), [today]);
  const history = recentDates.slice(0, -1).map((date) => state.entries[date] ?? createEntry(date));
  const weeklyWorkoutDates = new Set(weeklyWorkouts.map(workoutDateKey).filter(Boolean));
  const weeklyEntries = recentDates.map((date) => ({ date, entry: state.entries[date] ?? createEntry(date) }));
  const activeDays = weeklyEntries.filter(({ date, entry: item }) => item.habits.movement || item.workoutType !== "none" || weeklyWorkoutDates.has(date)).length;
  const insightMetrics: InsightMetric[] = [
    { id: "morning", label: "Morning routine", completedDays: weeklyEntries.filter(({ entry: item }) => item.habits.morning).length, suggestion: "Protect the first 15 minutes of your day from your phone and follow one repeatable start." },
    { id: "outside", label: "Time outside", completedDays: weeklyEntries.filter(({ entry: item }) => item.habits.outside).length, suggestion: "Schedule a 10-minute daylight break before lunch, even on busy days." },
    { id: "movement", label: "Movement", completedDays: activeDays, suggestion: "Use a 20-minute walk or mobility session as your minimum on days without a full workout." },
    { id: "winddown", label: "Evening wind-down", completedDays: weeklyEntries.filter(({ entry: item }) => item.habits.winddown).length, suggestion: "Set a consistent 20-minute wind-down cue and lower the lights before bed." },
    { id: "water", label: "Water goal", completedDays: weeklyEntries.filter(({ entry: item }) => item.water >= 8).length, suggestion: "Fill your bottle in the morning and aim to finish half of your water before lunch." },
  ];
  const focusArea = [...insightMetrics].sort((a, b) => a.completedDays - b.completedDays)[0];
  const focusTarget = Math.min(7, Math.max(4, focusArea.completedDays + 2));
  const anchorCompletions = weeklyEntries.reduce((total, { entry: item }) => total + Object.values(item.habits).filter(Boolean).length, 0);
  const averageWater = weeklyEntries.reduce((total, { entry: item }) => total + item.water, 0) / weeklyEntries.length;
  const loggedDays = weeklyEntries.filter(({ date }) => Boolean(state.entries[date]) || weeklyWorkoutDates.has(date)).length;
  const wellnessScore = score(entry, oura);
  const plan = prescription(entry, history, oura, limit, equipment, override);
  const update = (next: Entry) => setState((current) => ({ ...current, entries: { ...current.entries, [next.date]: next } }));
  const setField = <Key extends keyof Entry>(key: Key, value: Entry[Key]) => update({ ...entry, [key]: value });
  const toggle = (id: string) => update({ ...entry, habits: { ...entry.habits, [id]: !entry.habits[id] } });
  function touchStart(event: TouchEvent<HTMLElement>) { if (window.scrollY <= 0 && !refreshing) refreshStart.current = event.touches[0].clientY; }
  function touchMove(event: TouchEvent<HTMLElement>) { if (refreshStart.current === null || refreshing) return; const distance = event.touches[0].clientY - refreshStart.current; const next = distance > 0 ? Math.min(distance * .55, 92) : 0; refreshDistance.current = next; setRefreshProgress(next); }
  function touchEnd() { refreshStart.current = null; if (refreshDistance.current >= 70) { setRefreshing(true); window.setTimeout(() => window.location.reload(), 220); } else { refreshDistance.current = 0; setRefreshProgress(0); } }

  return <main className="wellness-app" onTouchCancel={touchEnd} onTouchEnd={touchEnd} onTouchMove={touchMove} onTouchStart={touchStart}>
    <div className={refreshProgress || refreshing ? "refresh-indicator refresh-indicator-visible" : "refresh-indicator"} style={{ transform: `translate(-50%, ${Math.max(refreshProgress - 58, -58)}px)` }}>{refreshing ? "Refreshing" : refreshProgress >= 70 ? "Release to refresh" : "Pull to refresh"}</div>
    <div className="wellness-shell">
      {tab === "prescription" && <section className="page-section prescription-detail">
        <header className="rx-overview">
          <div className="rx-topline"><span className="rx-mark"><Pill aria-hidden="true" size={17} strokeWidth={2.2} /> Daily prescription</span><span className="rx-mode">{plan.mode}</span></div>
          <p className="rx-date">{new Intl.DateTimeFormat("en-US", { weekday: "long", month: "short", day: "numeric" }).format(new Date(`${selectedDate}T12:00:00`))}</p>
          <h2>{plan.title}</h2>
          <p className="rx-intro">A clear plan shaped by your Oura recovery signals and recent movement.</p>
          <div className="rx-signals" aria-label="Oura signals used for this prescription"><span><strong>{oura?.readinessScore ?? "--"}</strong><small>readiness</small></span><span><strong>{oura?.sleepScore ?? "--"}</strong><small>sleep</small></span><span><strong>{oura?.activityScore ?? "--"}</strong><small>activity</small></span></div>
        </header>
        <div className="rx-plan-layout">
          <section className="rx-training" aria-labelledby="rx-training-title">
            <div className="rx-section-heading"><span className="rx-section-icon"><Dumbbell aria-hidden="true" size={19} strokeWidth={2} /></span><div><p>Training dose</p><h3 id="rx-training-title">Today&apos;s movement</h3></div><small>{plan.moves.length} steps</small></div>
            <ol className="rx-move-list">{plan.moves.map((move, index) => <li key={move}><span>{String(index + 1).padStart(2, "0")}</span><p>{move}</p></li>)}</ol>
          </section>
          <aside className="rx-support-stack" aria-label="Recovery and nutrition support">
            <section className="rx-support-block"><div className="rx-section-heading"><span className="rx-section-icon rx-recovery-icon"><HeartPulse aria-hidden="true" size={19} strokeWidth={2} /></span><div><p>Recovery dose</p><h3>Restore well</h3></div></div><ul>{plan.recovery.map((item) => <li key={item}>{item}</li>)}</ul></section>
            <section className="rx-support-block"><div className="rx-section-heading"><span className="rx-section-icon rx-food-icon"><Salad aria-hidden="true" size={19} strokeWidth={2} /></span><div><p>Nutrition dose</p><h3>Food focus</h3></div></div><ul>{plan.food.map((item) => <li key={item}>{item}</li>)}</ul></section>
          </aside>
        </div>
        <section className="rx-why"><div className="rx-why-icon"><Activity aria-hidden="true" size={20} strokeWidth={2} /></div><div><strong>Why this prescription</strong><p>{plan.reason}</p></div><button onClick={() => setTab("today")} type="button"><ArrowLeft aria-hidden="true" size={17} strokeWidth={2} /> Today</button></section>
      </section>}
      {tab === "today" && <>
        <section className="welcome-row"><div className={`score-panel ${scoreBand(wellnessScore)}`} style={{ "--score-progress": `${wellnessScore}%` } as React.CSSProperties}><div className="score-panel-top"><span className="score-title"><Activity aria-hidden="true" size={18} strokeWidth={2} /> Self-care score</span><span className="score-state">{scoreState(wellnessScore)}</span></div><div className="score-value"><strong>{wellnessScore}</strong><span>/100</span></div><div className="score-meter" aria-label={`Self-care score ${wellnessScore} out of 100`} role="img"><span /></div><div className="score-scale" aria-hidden="true"><span>Needs care</span><span>Building</span><span>Strong care</span></div><p>{scoreMessage(wellnessScore)}</p></div>{connected && <div className="oura-inline" aria-label="Oura recovery inputs"><span><strong>{oura?.readinessScore ?? "--"}</strong><small>readiness</small></span><span><strong>{oura?.sleepScore ?? "--"}</strong><small>sleep</small></span><span><strong>{oura?.activityScore ?? "--"}</strong><small>activity</small></span><span><strong>{oura?.steps?.toLocaleString() ?? "--"}</strong><small>steps</small></span></div>}<div><p className="eyebrow">Your care today</p><h2>{selectedDate === today ? "How are you caring for yourself?" : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric" }).format(new Date(`${selectedDate}T12:00:00`))}</h2><p className="muted">Small acts of care add up.</p></div></section>
        <nav className="date-strip" aria-label="Recent days">{recentDates.map((date) => <button className={selectedDate === date ? "date-pill date-pill-active" : "date-pill"} key={date} onClick={() => setSelectedDate(date)} type="button"><span>{new Intl.DateTimeFormat("en-US", { weekday: "short" }).format(new Date(`${date}T12:00:00`))}</span><strong>{new Date(`${date}T12:00:00`).getDate()}</strong><i className={state.entries[date] ? "date-dot date-dot-filled" : "date-dot"} /></button>)}</nav>
        {connected && <section className="oura-snapshot"><div><p className="eyebrow">Oura sync</p><h3>Recovery inputs</h3><p className="muted">{oura?.syncedAt ? `Checked at ${new Date(oura.syncedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}` : "Waiting for sync"}</p></div><div className="oura-stats"><span><strong>{oura?.readinessScore ?? "--"}</strong><small>readiness</small></span><span><strong>{oura?.sleepScore ?? "--"}</strong><small>sleep score</small></span><span><strong>{oura?.activityScore ?? "--"}</strong><small>activity</small></span><span><strong>{oura?.steps?.toLocaleString() ?? "--"}</strong><small>steps</small></span></div></section>}
        <div className="wellness-grid"><section className="surface habit-surface"><div className="section-heading"><div><p className="eyebrow">Daily anchors</p><h3>Keep it simple</h3></div><span className="section-count">{Object.values(entry.habits).filter(Boolean).length}/{HABITS.length}</span></div><div className="habit-list">{HABITS.map((habit) => <button className={entry.habits[habit.id] ? "habit-row habit-row-done" : "habit-row"} key={habit.id} onClick={() => toggle(habit.id)} type="button"><span className="habit-check">{entry.habits[habit.id] ? "✓" : ""}</span><span className="habit-copy"><strong>{habit.label}</strong><small>{habit.detail}</small></span><span className="habit-arrow">›</span></button>)}</div></section><section className="surface hydration-surface"><div className="section-heading"><div><p className="eyebrow">Hydration</p><h3>Water check</h3></div><strong className="big-number">{entry.water}<small>/ 8 glasses</small></strong></div><div className="glass-row">{Array.from({ length: 8 }, (_, index) => <button className={index < entry.water ? "water-glass water-glass-full" : "water-glass"} key={index} onClick={() => setField("water", index + 1 === entry.water ? index : index + 1)} type="button" aria-label={`Set water to ${index + 1} glasses`}><span /></button>)}</div><p className="muted">Tap a glass to log where you are.</p></section><section className="surface note-surface"><div className="section-heading"><div><p className="eyebrow">Reflection</p><h3>Leave a note</h3></div><span className="note-prompt">What helped today?</span></div><textarea aria-label="Daily reflection" onChange={(event) => setField("note", event.target.value)} placeholder="A win, a worry, something you noticed..." value={entry.note} /></section></div>
      </>}
      {tab === "exercise" && <section className="page-section"><p className="eyebrow">Movement and recovery</p><h2>Exercise</h2><p className="muted">Your prescription for today, followed by the movement Oura has recorded recently.</p><section className="exercise-prescription"><div className="exercise-prescription-heading"><div><p className="prescription-support-label">Today&apos;s plan</p><h3>{plan.title}</h3></div><span className="prescription-label">{planDayType(plan)}</span></div><p className="rotation-note">Training emphasis adjusts around your recent movement history when Oura data allows.</p><ol className="exercise-moves">{plan.moves.map((move) => <li key={move}><label className="exercise-check"><input checked={Boolean(checkedMoves[move])} onChange={(event) => setCheckedMoves((current) => ({ ...current, [move]: event.target.checked }))} type="checkbox" /><span>{move}</span></label></li>)}</ol><p className="exercise-progress">{Object.values(checkedMoves).filter(Boolean).length} of {plan.moves.length} movements complete</p><div className="exercise-support-grid"><div><p className="prescription-support-label">Stretch + recovery</p><ul>{plan.recovery.map((item) => <li key={item}>{item}</li>)}</ul></div></div><div className="effort-check"><label>How did this effort feel?<select value={effort} onChange={(event) => { const value = event.target.value; setEffort(value); setOverride(value === "too-hard" ? "recover" : value === "too-easy" ? "push" : "auto"); }}><option value="right">About right</option><option value="too-easy">Too easy</option><option value="too-hard">Too hard</option></select></label>{effort === "too-hard" && <small>We&apos;ll favor a lighter recovery day next.</small>}{effort === "too-easy" && <small>We&apos;ll consider a stronger session next time.</small>}</div></section><h3 className="exercise-history-heading">Recent sessions</h3>{connected ? <div className="exercise-list">{oura?.workouts?.length ? oura.workouts.map((workout, index) => <article className="exercise-row" key={`${workout.id || index}`}><div className="exercise-icon">{workoutName(workout).slice(0, 1).toUpperCase()}</div><div><strong>{workoutName(workout)}</strong><small>{workoutDate(workout) || "Recent activity"}</small></div><span>{workoutSummary(workout)}</span></article>) : <div className="empty-state"><strong>No recent workouts found</strong><p>Sync your Oura ring, then pull down to refresh.</p></div>}</div> : <div className="empty-state"><strong>Connect Oura to see exercise</strong><p>Your workouts, duration, and activity details will appear here.</p><a href="/api/integrations/oura/start">Log in to Oura</a></div>}</section>}
      {tab === "trends" && <section className="page-section insights-page"><p className="eyebrow">Patterns, not perfection</p><h2>Insights</h2><p className="muted">A weekly view of what is working, what is slipping, and where a little attention could help most.</p><section className="insight-focus" aria-labelledby="weekly-focus-title"><div className="insight-focus-icon"><Target aria-hidden="true" size={22} strokeWidth={2} /></div><div><p className="insight-label">Your focus this week</p><h3 id="weekly-focus-title">{focusArea.label}</h3><p>{focusArea.suggestion}</p></div><div className="insight-focus-target"><strong>{focusTarget}</strong><span>day target</span></div></section><div className="insight-stats" aria-label="Weekly summary"><div><strong>{loggedDays}<span>/7</span></strong><small>days logged</small></div><div><strong>{anchorCompletions}<span>/28</span></strong><small>anchors kept</small></div><div><strong>{averageWater.toFixed(1)}<span>/8</span></strong><small>avg water</small></div><div><strong>{activeDays}<span>/7</span></strong><small>active days</small></div></div><section className="insight-breakdown"><div className="insight-heading"><div><p className="insight-label">Areas to watch</p><h3>Weekly consistency</h3></div><span>{insightMetrics.filter((metric) => metric.completedDays <= 3).length} need attention</span></div><div className="insight-list">{[...insightMetrics].sort((a, b) => a.completedDays - b.completedDays).map((metric) => <div className="insight-row" key={metric.id}><div><strong>{metric.label}</strong><small>{metric.completedDays === 7 ? "Kept every day" : `${7 - metric.completedDays} days missed`}</small></div><div className="insight-bar" aria-label={`${metric.label}: ${metric.completedDays} of 7 days`} role="img"><span style={{ width: `${metric.completedDays / 7 * 100}%` }} /></div><output>{metric.completedDays}/7</output></div>)}</div></section><section className="daily-rhythm"><div className="insight-heading"><div><p className="insight-label">Daily rhythm</p><h3>How the week moved</h3></div><span>anchors + water</span></div><div className="trend-grid">{weeklyEntries.map(({ date, entry: item }) => { const completion = dailyCompletion(item, weeklyWorkoutDates.has(date)); return <div className="trend-row" key={date}><strong>{new Intl.DateTimeFormat("en-US", { weekday: "short" }).format(new Date(`${date}T12:00:00`))}</strong><div className="trend-bar"><span style={{ width: `${completion}%` }} /></div><output>{completion}%</output></div>; })}</div></section></section>}
      {tab === "history" && <section className="page-section"><p className="eyebrow">Your record</p><h2>Past check-ins</h2><p className="muted">Tap a day to reopen its reflection and prescription.</p><div className="history-list">{Object.values(state.entries).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 30).map((item) => <button key={item.date} onClick={() => { setSelectedDate(item.date); setTab("today"); }} type="button"><span><strong>{item.date}</strong><small>{item.workoutType === "none" ? "No workout logged" : item.workoutType} {item.note ? " / note saved" : ""}</small></span><output>{score(item)}</output></button>)}</div></section>}
      {tab === "settings" && <section className="page-section"><p className="eyebrow">Your space</p><h2>Settings</h2><div className="settings-list"><div><strong>Oura connection</strong><small>{connected ? "Connected and read-only" : "Not connected"}</small><a href="/api/integrations/oura/start">{connected ? "Reconnect Oura" : "Log in to Oura"}</a></div><div><strong>Privacy</strong><small>Your check-ins are stored on this device.</small><button onClick={() => { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `well-being-${today}.json`; link.click(); URL.revokeObjectURL(url); }} type="button">Export my data</button><button className="danger-link" onClick={() => { if (window.confirm("Delete all local check-ins?")) { setState({ entries: {} }); window.localStorage.removeItem(STORAGE_KEY); } }} type="button">Delete local data</button></div></div></section>}
      <nav className="bottom-nav" aria-label="Main navigation">{tabs.map((item) => { const Icon = tabIcon(item.id); return <button aria-label={item.label} className={tab === item.id ? "bottom-nav-active" : ""} key={item.id} onClick={() => setTab(item.id)} type="button"><span className="nav-icon"><Icon aria-hidden="true" size={18} strokeWidth={2} /></span><span className="nav-label">{item.label}</span></button>; })}</nav>
      <footer className="privacy-note"><span className="privacy-dot" /> Your check-ins stay on this device.</footer>
    </div>
  </main>;
}
