"use client";

import { type TouchEvent, useEffect, useMemo, useRef, useState } from "react";

type WorkoutType = "none" | "strength" | "run" | "cycle" | "sport" | "mobility";
type Entry = { date: string; habits: Record<string, boolean>; water: number; movement: number; workoutType: WorkoutType; note: string };
type State = { entries: Record<string, Entry> };
type OuraWorkout = Record<string, unknown>;
type Oura = { sleepScore?: number; readinessScore?: number; activityScore?: number; steps?: number; recentWorkouts?: string[]; workouts?: OuraWorkout[]; syncedAt?: string };
type Tab = "today" | "exercise" | "prescription" | "trends" | "history" | "settings";
type Prescription = { mode: string; title: string; reason: string; moves: string[]; recovery: string[]; food: string[] };

const STORAGE_KEY = "personal-wellness-journal";
const HABITS = [{ id: "morning", label: "Morning routine", detail: "Start without the scroll" }, { id: "outside", label: "Time outside", detail: "A little daylight counts" }, { id: "movement", label: "Move your body", detail: "Walk, train, stretch" }, { id: "winddown", label: "Evening wind-down", detail: "Make room for rest" }];
const tabs: { id: Tab; label: string }[] = [{ id: "today", label: "Today" }, { id: "exercise", label: "Exercise" }, { id: "prescription", label: "Plan" }, { id: "trends", label: "Trends" }, { id: "settings", label: "Settings" }];

function dateKey(date = new Date()) { return date.toISOString().slice(0, 10); }
function createEntry(date: string): Entry { return { date, habits: Object.fromEntries(HABITS.map((habit) => [habit.id, false])), water: 0, movement: 0, workoutType: "none", note: "" }; }
function normalize(entry: Partial<Entry>, date: string): Entry { return { ...createEntry(date), ...entry, habits: { ...createEntry(date).habits, ...entry.habits } }; }
function score(entry: Entry, oura?: Oura | null) { const personal = (Object.values(entry.habits).filter(Boolean).length / HABITS.length + Math.min(entry.water / 8, 1)) / 2; const signals = [oura?.readinessScore, oura?.sleepScore, oura?.activityScore].filter((v): v is number => typeof v === "number"); return Math.round((signals.length ? signals.reduce((a, b) => a + b, 0) / signals.length / 100 * .65 + personal * .35 : personal) * 100); }
function prescription(entry: Entry, history: Entry[], oura: Oura | null, limit: string, equipment: string, override: string): Prescription {
  const readiness = oura?.readinessScore ?? 70;
  const sleep = oura?.sleepScore ?? 70;
  const hardRun = [...history, entry].some((item) => item.workoutType === "run" && item.movement >= 35) || Boolean(oura?.recentWorkouts?.some((item) => /run|cycle|hike/i.test(item)));
  if (override === "recover" || readiness < 60 || sleep < 60) return { mode: "Recovery", title: "Recover on purpose", reason: "Your recent recovery signals call for low intensity and more room to rebuild.", moves: ["20 min easy walk", "2 rounds: 8 cat-cows + 8 world's greatest stretches per side", "10 min gentle mobility"], recovery: ["Breathe slowly for 3 minutes", "Keep effort conversational and finish feeling better"], food: ["Protein at each meal: eggs, yogurt, chicken, fish, tofu", "Colorful produce, soup, rice, potatoes, and steady fluids"] };
  if (override === "push" || (readiness >= 82 && sleep >= 80)) return { mode: "Build", title: "Train with intent", reason: "Your sleep and readiness support a focused training day.", moves: ["Warm-up: 6 min brisk walk + mobility", equipment === "none" ? "Tempo squats: 4 x 10" : "Squat or leg press: 4 x 6-8", equipment === "none" ? "Push-ups: 4 x 8-15" : "Bench press: 4 x 6-10", "Romanian deadlift: 3 x 8-10", "Farmer carry: 4 x 40 sec"], recovery: ["8-10 min full-body stretching", "Easy walk later if stiff; protect tonight's sleep"], food: ["Protein at every meal: beef, poultry, fish, eggs, dairy, tofu", "Add carbs around training: oats, rice, potatoes, fruit", "Have a protein plus carb meal after training"] };
  if (hardRun) return { mode: "Balance", title: "Build the base", reason: "Recent activity has been demanding, so today balances strength and control.", moves: ["Goblet squat: 3 x 10", "Push-ups: 3 x 8-12", "1-arm row: 3 x 10 per side", "Dead bug: 3 x 8 per side", "10 min easy walk"], recovery: ["5-8 min calves, hips, and hamstrings", "Keep the next session easy if soreness rises"], food: ["Protein-forward meals: lean meat, fish, cottage cheese, beans", "Moderate carbs: oats, potatoes, rice, fruit", "Add vegetables and healthy fats"] };
  return { mode: "Steady", title: "Move and reset", reason: `A moderate session fits your current signals. ${limit} minute target.`, moves: ["5 min easy warm-up", "Run/walk intervals: 8 x 1 min steady, 1 min easy", equipment === "none" ? "Reverse lunges: 3 x 8 per side" : "Split squat: 3 x 8 per side", "Plank: 3 x 30-45 sec"], recovery: ["5 min slow breathing after training", "Gentle stretch for calves, hips, chest, and back"], food: ["Balanced plates: protein, whole-food carbs, vegetables", "Choose chicken, lentils, eggs, yogurt, rice, fruit, and greens", "Pair snacks with protein"] };
}
function workoutName(workout: OuraWorkout) { return String(workout.type || workout.activity || workout.name || workout.label || "Workout").replaceAll("_", " "); }
function workoutDate(workout: OuraWorkout) { return String(workout.day || workout.start_datetime || workout.start_time || ""); }
function workoutDuration(workout: OuraWorkout) { const seconds = Number(workout.duration || workout.duration_seconds); return Number.isFinite(seconds) && seconds > 0 ? `${Math.round(seconds / 60)} min` : "Duration unavailable"; }

export default function Home() {
  const today = dateKey();
  const [state, setState] = useState<State>({ entries: {} });
  const [oura, setOura] = useState<Oura | null>(null);
  const [connected, setConnected] = useState(false);
  const [tab, setTab] = useState<Tab>("today");
  const [selectedDate, setSelectedDate] = useState(today);
  const [loaded, setLoaded] = useState(false);
  const [limit, setLimit] = useState("45");
  const [equipment, setEquipment] = useState("gym");
  const [override, setOverride] = useState("auto");
  const [started, setStarted] = useState(false);
  const [complete, setComplete] = useState(false);
  useEffect(() => { if (complete) setStarted(true); }, [complete]);
  const refreshStart = useRef<number | null>(null);
  const refreshDistance = useRef(0);
  const [refreshing, setRefreshing] = useState(false);
  const [refreshProgress, setRefreshProgress] = useState(0);

  useEffect(() => { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) { try { const parsed = JSON.parse(saved) as State; setState({ entries: Object.fromEntries(Object.entries(parsed.entries || {}).map(([date, item]) => [date, normalize(item, date)])) }); } catch { window.localStorage.removeItem(STORAGE_KEY); } } setLoaded(true); }, []);
  useEffect(() => { if (loaded) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [loaded, state]);
  useEffect(() => { void fetch("/api/integrations/status").then(async (response) => { if (response.ok) setConnected(Boolean((await response.json() as { oura?: boolean }).oura)); }); }, []);
  useEffect(() => { if (!connected) return; void fetch(`/api/integrations/oura/data?date=${selectedDate}`).then(async (response) => { if (!response.ok) return; const data = await response.json() as { sleep?: Record<string, unknown>; readiness?: Record<string, unknown>; activity?: Record<string, unknown>; workouts?: OuraWorkout[] }; const sleep = data.sleep || {}; const readiness = data.readiness || {}; const activity = data.activity || {}; const workouts = data.workouts || []; setOura({ sleepScore: Number(sleep.score) || undefined, readinessScore: Number(readiness.score) || undefined, activityScore: Number(activity.score) || undefined, steps: Number(activity.steps) || undefined, workouts, recentWorkouts: workouts.map(workoutName), syncedAt: new Date().toISOString() }); }); }, [connected, selectedDate]);

  const entry = state.entries[selectedDate] ?? createEntry(selectedDate);
  const recentDates = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(`${today}T12:00:00`); date.setDate(date.getDate() - (6 - index)); return dateKey(date); }), [today]);
  const history = recentDates.slice(0, -1).map((date) => state.entries[date] ?? createEntry(date));
  const wellnessScore = score(entry, oura);
  const plan = prescription(entry, history, oura, limit, equipment, override);
  const update = (next: Entry) => setState((current) => ({ ...current, entries: { ...current.entries, [next.date]: next } }));
  const setField = <Key extends keyof Entry>(key: Key, value: Entry[Key]) => update({ ...entry, [key]: value });
  const toggle = (id: string) => update({ ...entry, habits: { ...entry.habits, [id]: !entry.habits[id] } });
  function touchStart(event: TouchEvent<HTMLElement>) { if (window.scrollY <= 0 && !refreshing) refreshStart.current = event.touches[0].clientY; }
  function touchMove(event: TouchEvent<HTMLElement>) { if (refreshStart.current === null || refreshing) return; const distance = event.touches[0].clientY - refreshStart.current; const next = distance > 0 ? Math.min(distance * .55, 92) : 0; refreshDistance.current = next; setRefreshProgress(next); }
  function touchEnd() { refreshStart.current = null; if (refreshDistance.current >= 70) { setRefreshing(true); window.setTimeout(() => window.location.reload(), 220); } else { refreshDistance.current = 0; setRefreshProgress(0); } }

  return <main className="wellness-app" onTouchCancel={touchEnd} onTouchEnd={touchEnd} onTouchMove={touchMove} onTouchStart={touchStart}>
    <div className={refreshProgress || refreshing ? "refresh-indicator refresh-indicator-visible" : "refresh-indicator"} style={{ transform: `translate(-50%, ${Math.max(refreshProgress - 58, -58)}px)` }}>{refreshing ? "Refreshing" : refreshProgress >= 70 ? "Release to refresh" : "Pull to refresh"}</div>
    <div className="wellness-shell">
      <header className="topbar"><div className="brand-lockup"><span className="brand-mark">W</span><div><p className="eyebrow">Personal wellness</p><h1>Well / Being</h1></div></div><button className="icon-button" onClick={() => { setSelectedDate(today); setTab("today"); }} type="button">Today</button></header>
      {tab === "prescription" && <section className="page-section prescription-detail"><p className="eyebrow">Your daily prescription</p><h2>{plan.title}</h2><p className="muted">A clear plan for today, shaped by your Oura recovery signals and recent movement.</p><div className="detail-grid"><article><p className="prescription-support-label">Training</p><ol>{plan.moves.map((move) => <li key={move}>{move}</li>)}</ol></article><article><p className="prescription-support-label">Stretch + recovery</p><ul>{plan.recovery.map((item) => <li key={item}>{item}</li>)}</ul></article><article><p className="prescription-support-label">Food focus</p><ul>{plan.food.map((item) => <li key={item}>{item}</li>)}</ul></article></div><div className="prescription-why"><strong>Why this plan</strong><p>{plan.reason} Oura readiness: {oura?.readinessScore ?? "--"}. Sleep score: {oura?.sleepScore ?? "--"}. Activity score: {oura?.activityScore ?? "--"}.</p></div><button className="prescription-primary detail-action" onClick={() => setTab("today")} type="button">Back to today</button></section>}
      {tab === "today" && <>
        <section className="welcome-row"><div><p className="eyebrow">Your daily reset</p><h2>{selectedDate === today ? "How are you, really?" : selectedDate}</h2><p className="muted">Small signals. Better decisions. A little more of you.</p></div><div className="score-ring" style={{ "--score": `${wellnessScore * 3.6}deg` } as React.CSSProperties}><strong>{wellnessScore}</strong><span>wellness<br />score</span></div></section>
        <nav className="date-strip" aria-label="Recent days">{recentDates.map((date) => <button className={selectedDate === date ? "date-pill date-pill-active" : "date-pill"} key={date} onClick={() => setSelectedDate(date)} type="button"><span>{new Intl.DateTimeFormat("en-US", { weekday: "short" }).format(new Date(`${date}T12:00:00`))}</span><strong>{new Date(`${date}T12:00:00`).getDate()}</strong><i className={state.entries[date] ? "date-dot date-dot-filled" : "date-dot"} /></button>)}</nav>
        <section className="prescription-card"><div className="prescription-intro"><p className="eyebrow">Today&apos;s prescription</p><h3>{plan.title}</h3><p>{plan.reason}</p></div><span className="prescription-label">{plan.mode}</span><div className="prescription-controls"><label>Time<select value={limit} onChange={(event) => setLimit(event.target.value)}><option value="20">20 min</option><option value="30">30 min</option><option value="45">45 min</option><option value="60">60 min</option></select></label><label>Equipment<select value={equipment} onChange={(event) => setEquipment(event.target.value)}><option value="gym">Gym</option><option value="home">Home basics</option><option value="none">No equipment</option></select></label><label>Override<select value={override} onChange={(event) => setOverride(event.target.value)}><option value="auto">Trust Oura</option><option value="push">I feel ready</option><option value="recover">I feel run down</option></select></label></div><ol className="prescription-list">{plan.moves.map((move) => <li key={move}>{move}</li>)}</ol><div className="prescription-support"><div><p className="prescription-support-label">Stretch + recovery</p><ul>{plan.recovery.map((item) => <li key={item}>{item}</li>)}</ul></div><div><p className="prescription-support-label">Food focus</p><ul>{plan.food.map((item) => <li key={item}>{item}</li>)}</ul></div></div><button className="prescription-primary" onClick={() => { setStarted(true); setComplete(false); }} type="button">{started ? "Workout in progress" : "Start this plan"}</button>{started && <button className="prescription-complete" onClick={() => { setComplete(true); setStarted(false); }} type="button">{complete ? "Completed today" : "Mark workout complete"}</button>}</section>
        {connected && <section className="oura-snapshot"><div><p className="eyebrow">Oura sync</p><h3>Recovery inputs</h3><p className="muted">{oura?.syncedAt ? `Checked at ${new Date(oura.syncedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}` : "Waiting for sync"}</p></div><div className="oura-stats"><span><strong>{oura?.readinessScore ?? "--"}</strong><small>readiness</small></span><span><strong>{oura?.sleepScore ?? "--"}</strong><small>sleep score</small></span><span><strong>{oura?.activityScore ?? "--"}</strong><small>activity</small></span><span><strong>{oura?.steps?.toLocaleString() ?? "--"}</strong><small>steps</small></span></div></section>}
        <div className="wellness-grid"><section className="surface habit-surface"><div className="section-heading"><div><p className="eyebrow">Daily anchors</p><h3>Keep it simple</h3></div><span className="section-count">{Object.values(entry.habits).filter(Boolean).length}/{HABITS.length}</span></div><div className="habit-list">{HABITS.map((habit) => <button className={entry.habits[habit.id] ? "habit-row habit-row-done" : "habit-row"} key={habit.id} onClick={() => toggle(habit.id)} type="button"><span className="habit-check">{entry.habits[habit.id] ? "✓" : ""}</span><span className="habit-copy"><strong>{habit.label}</strong><small>{habit.detail}</small></span><span className="habit-arrow">›</span></button>)}</div></section><section className="surface hydration-surface"><div className="section-heading"><div><p className="eyebrow">Hydration</p><h3>Water check</h3></div><strong className="big-number">{entry.water}<small>/ 8 glasses</small></strong></div><div className="glass-row">{Array.from({ length: 8 }, (_, index) => <button className={index < entry.water ? "water-glass water-glass-full" : "water-glass"} key={index} onClick={() => setField("water", index + 1 === entry.water ? index : index + 1)} type="button" aria-label={`Set water to ${index + 1} glasses`}><span /></button>)}</div><p className="muted">Tap a glass to log where you are.</p></section><section className="surface note-surface"><div className="section-heading"><div><p className="eyebrow">Reflection</p><h3>Leave a note</h3></div><span className="note-prompt">What helped today?</span></div><textarea aria-label="Daily reflection" onChange={(event) => setField("note", event.target.value)} placeholder="A win, a worry, something you noticed..." value={entry.note} /></section></div>
      </>}
      {tab === "exercise" && <section className="page-section"><p className="eyebrow">Oura history</p><h2>Your movement record</h2><p className="muted">Recent workouts from Oura, kept separate so today&apos;s plan stays easy to scan.</p>{connected ? <div className="exercise-list">{oura?.workouts?.length ? oura.workouts.map((workout, index) => <article className="exercise-row" key={`${workout.id || index}`}><div className="exercise-icon">{workoutName(workout).slice(0, 1).toUpperCase()}</div><div><strong>{workoutName(workout)}</strong><small>{workoutDate(workout) || "Recent activity"}</small></div><span>{workoutDuration(workout)}</span></article>) : <div className="empty-state"><strong>No recent workouts found</strong><p>Sync your Oura ring, then pull down to refresh.</p></div>}</div> : <div className="empty-state"><strong>Connect Oura to see exercise</strong><p>Your workouts, duration, and activity details will appear here.</p><a href="/api/integrations/oura/start">Log in to Oura</a></div>}</section>}
      {tab === "trends" && <section className="page-section"><p className="eyebrow">Patterns, not perfection</p><h2>Your week at a glance</h2><p className="muted">Use trends to notice what helps, not to grade yourself.</p><div className="trend-grid">{recentDates.map((date) => { const item = state.entries[date] ?? createEntry(date); return <div className="trend-row" key={date}><strong>{new Intl.DateTimeFormat("en-US", { weekday: "short" }).format(new Date(`${date}T12:00:00`))}</strong><div className="trend-bar"><span style={{ width: `${score(item)}%` }} /></div><output>{score(item)}</output></div>; })}</div></section>}
      {tab === "history" && <section className="page-section"><p className="eyebrow">Your record</p><h2>Past check-ins</h2><p className="muted">Tap a day to reopen its reflection and prescription.</p><div className="history-list">{Object.values(state.entries).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 30).map((item) => <button key={item.date} onClick={() => { setSelectedDate(item.date); setTab("today"); }} type="button"><span><strong>{item.date}</strong><small>{item.workoutType === "none" ? "No workout logged" : item.workoutType} {item.note ? " / note saved" : ""}</small></span><output>{score(item)}</output></button>)}</div></section>}
      {tab === "settings" && <section className="page-section"><p className="eyebrow">Your space</p><h2>Settings</h2><div className="settings-list"><div><strong>Oura connection</strong><small>{connected ? "Connected and read-only" : "Not connected"}</small><a href="/api/integrations/oura/start">{connected ? "Reconnect Oura" : "Log in to Oura"}</a></div><div><strong>Privacy</strong><small>Your check-ins are stored on this device.</small><button onClick={() => { const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `well-being-${today}.json`; link.click(); URL.revokeObjectURL(url); }} type="button">Export my data</button><button className="danger-link" onClick={() => { if (window.confirm("Delete all local check-ins?")) { setState({ entries: {} }); window.localStorage.removeItem(STORAGE_KEY); } }} type="button">Delete local data</button></div></div></section>}
      <nav className="bottom-nav" aria-label="Main navigation">{tabs.map((item) => <button className={tab === item.id ? "bottom-nav-active" : ""} key={item.id} onClick={() => setTab(item.id)} type="button">{item.label}</button>)}</nav>
      <footer className="privacy-note"><span className="privacy-dot" /> Your check-ins stay on this device.</footer>
    </div>
  </main>;
}
